### ISSUE TITLE
Flutter SDK installation is failed of orb 2.0.3

### ISSUE THREAD

**Issue by KevinJ1008** [CircleCI-Public/flutter-orb#36]
## Orb version:
2.0.3

## What happened:
Installing Flutter SDK is failed

## Expected behavior:
Flutter SDK should be install success

## Additional Information:
I try to use `2.0.3` to test installing flutter SDK in arm architecture could work or not, but I got failing result. The orb version I used is: https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:b473172d318fb10def77644e0b8cace70c2acd6a

Then I found there is an incorrect env key after checking script in `install-sdk.sh`:
![image](https://github.com/CircleCI-Public/flutter-orb/assets/40198844/a2e86264-db54-418b-b155-630b2c0b6c9b)
It should be `ORB_VAL_FLUTTER_SDK_VERSION` instead of `ORB_VAL_FLUTTER_SK_VERSION`

**Comment by zaki-arain** [comment]
This should be addressed in #44  , which is now released as v2.0.4. Thank you for your contribution towards this release! Please try to to use `circleci/flutter-orb@2.0.4`, thank you again!
