### ISSUE TITLE
Build failed for flutter 3.16.0

### ISSUE THREAD

**Issue by rsys-zeeshan-iqbal** [CircleCI-Public/flutter-orb#38]
## What happened:

Build fail because of version 

## Expected behavior:

Flutter version 3.16.0 is not supporting in current orbs version

## Additional Information:

`Because ally requires SDK version >=3.0.0 <3.16.0, version solving failed.
pub get failed
command: "/sdks/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/sdks/flutter",
  "PUB_ENVIRONMENT": "flutter_bot:flutter_cli:get",
  "PUB_CACHE": "/root/.pub-cache",
}
exit code: 1`

**Comment by marboledacci** [comment]
This should have been resolved by #44.
