### ISSUE TITLE
Is version 2.0.3 published?

### ISSUE THREAD

**Issue by Mehdi-Sohrabi0** [CircleCI-Public/flutter-orb#43]
## What happened:

Cannot find `circleci/flutter@2.0.3` in the orb registry. Check that the namespace, orb name and version are correct.

## Expected behavior:

The latest version (`2.0.3`) is not published on cci.

I have trouble running version `2.0.2` with `macos.m1.large.gen1`, I can see that there is a fix in the latest commit for this problem, but the pipeline for that is failed, and the latest version is still `2.0.2` while it should be `2.0.3`.

**Comment by rMozes** [comment]
Facing the same issue

**Comment by mlb5000** [comment]
Same. Since CircleCI are deprecating Intel MacOS, and M-series is all ARM, it makes Flutter builds unusable there. Please publish 2.0.3

**Comment by zaki-arain** [comment]
This should be addressed in #44  , which is now released as v2.0.4. Please try to to use `circleci/flutter-orb@2.0.4`, thank you!
